pull_request_rules:
  - name: Ping PR author when conflicting
    description: Warn the pull request author when their PR are conflicting
    conditions:
      - conflict
      - '-closed'
    actions:
      comment:
        message: >
          👋 @{{author}} your PR is conflicting and needs to be updated to be merged 😉
  - name: Ping PR author when title does not follow conventional commits
    description: Warn the pull request author when their PR title does not follow conventional commits
    conditions:
      - '-title ~= ^(fix|feat|docs|style|refactor|perf|test|build|ci|chore|revert)(?:(.+))?:'
    actions:
      comment:
        message: >-
          👋 @{{author}} your PR title does not follow conventional commits guidelines.
          ⚠️ If squashed, the new commit won't be complaint with those conventions 
          (please, refer to https://www.conventionalcommits.org/).
  - name: Automatic merge when CI passes and approved (rebase by default)
    conditions:
      - '#approved-reviews-by>=2'
      - check-success~=.*Success
      - base=main
      - label=auto-rebase
      - '-draft'
      - '-conflict'
    actions:
      merge:
        method: rebase
  - name: Automatic squash merge when CI passes and approved
    conditions:
      - '#approved-reviews-by>=2'
      - check-success~=.*Success
      - base=main
      - label=auto-squash
      - '-draft'
      - '-conflict'
    actions:
      merge:
        method: squash
  - name: Delete head branch after merge but not if other PRs depend on it
    conditions:
      - merged
    actions:
      delete_head_branch:
        force: false

merge_protections:
  - name: Make sure title follow conventional commits
    if:
      - base=main
    success_conditions:
      - title~=^(fix|feat|docs|style|refactor|perf|test|build|ci|chore|revert)(?:(.+))?:.*
