name: Test download artifact

on:
  workflow_call: 

jobs:
  Download-Artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - run: |
          echo "Github sha: ${{ github.sha }}"
      - name: Download artifact from another workflow
        uses: dawidd6/action-download-artifact@v15
        with:
          workflow: test-upload-download.yml
          commit: ${{ github.sha }}
          name: test-artifact
          workflow_conclusion: in_progress
          path: ./
      - run: cat test.txt