name: Test upload artifact

on:
  push:

jobs:
  Upload-Artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Create a file
        run: echo "This is a test file" > test.txt
      - name: Print workflow name
        run: echo "GitHub workflow ${{ github.workflow_ref }}"
      - name: Print workflow sha
        run: echo "GitHub sha ${{ github.sha }}"
      - name: Upload artifact
        uses: actions/upload-artifact@v4.5.0
        with:
          name: "test-artifact-${{ github.sha}}"
          path: ./test.txt
          if-no-files-found: error

  Call-Download:
    needs: Upload-Artifact
    uses: ./.github/workflows/test-download-artifact.yml
