name: A Matrix Workflow
on:
  push:
    tags: '*'
    branches-ignore:
      - 'autodelivery**'
      - 'bump-**'
      - 'renovate/**'
    paths-ignore: 
      - 'README.md'
      - 'CHANGELOG.md'
      - 'LICENSE'
  pull_request:
    branches: 
      - master
  workflow_dispatch:

jobs:
  Dispatcher:
    runs-on: ubuntu-latest
    if: >- # Prevents running the workflow twice on PR made by a branch of the same repository
      github.event_name != 'pull_request'
      || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - run: 'true'

  Build:
    needs: Dispatcher
    strategy:
      matrix:
        os: [windows, macos, ubuntu]
        jvm_version: [11, 17, 21] # Arbitrarily-made and arbitrarily-valued variables
        ruby_version: [2.7, 3.0]
        python_version: [3.12]
    runs-on: ${{ matrix.os }}-latest # The string is computed interpolating a variable value
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.jvm_version }} # "${{ }}" contents are interpreted by the github actions runner
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }} 
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
      - shell: bash
        run: java -version
      - shell: bash
        run: ruby --version
      - shell: bash
        run: python --version
      # - run: false

  Success:
    runs-on: ubuntu-22.04
    needs:
      - Build
    if: >-
      always() && (
        contains(join(needs.*.result, ','), 'failure')
        || (
          !contains(join(needs.*.result, ','), 'cancelled') 
          && !contains(join(needs.*.result, ','), 'skipped')
        )
      )
    steps:
      - name: Verify that there were no failures
        run: ${{ !contains(join(needs.*.result, ','), 'failure') }}
